### ISSUE TITLE
Changes to ScheduledDates

### ISSUE THREAD

**Issue by palomino79** [palomino79/notifier#4]
Given the nature of the message we send, we probably want  to actually preserve the original date string in ScheduledDates and save its upgraded datetime value to a different field. Or just use a cached property for it. 

 We also might not even want to use a dataclass for ScheduledDate, as we don't make use of it in any meaningful way.

Additionally, right now the scheduler expects everything to happen on a yearly basis, as the original design was meant to accommodate holidays and birthdays, which are by default once a year. Additional flexibility would allow this to function as a much more nuanced cronlike notification service. That said, I would not want to adopt the crontab entry syntax, as I think the ability to describe floating dates is a valuable feature of this service, as opposed to just a functional collection of crontab entries. 

Something like

```
date:
    day: 12
    month: each
notify_time: 12
```
or (this would just be each Monday, every week of the year)
```
date:
    weekday: monday
    month: each
notify_time: 12
```

where "each" is just a special value. This would add a lot of flexibility. Or, optionally, the ability to define a list of months and days, like

```
date:
    days:
        - 5
        - 10
        - 15
    months:
        - january
        - march
        - may
notify_time: 12
```

The most sensible implementation for this would be a collection of dataclasses for the date values where we attempt each one in sequence and handle the type error raised if the class can't be built with the provided values.
